# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
# default: &default
#   adapter: sqlite3
#   pool: 5
#   timeout: 5000

default: &default
  adapter: mysql2
  encoding: utf8
  port: <%= ENV['DB_PORT'] || 8889 %>
  pool: 5
  timeout: 5000
  host: <%= ENV['DB_HOST'] || 'dbserver'   %>
  database: <%= ENV['DB_NAME'] || 'blog' %>
  username: <%= ENV['DB_USER'] || 'root' %>
  password: <%= ENV['DB_PASSWORD'] || '' %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
